# Generated by Django 4.2 on 2024-09-12 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
